name: Learning GitHub Script

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find Exisitng Comment
        uses: actions/github-script@v5
        id: find-comment
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
             console.log(github.rest.issues.listComments({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo
             }))
      - name: Print comments
        run: echo "${{steps.find-comment.outputs.result}}"
           
