name: Learning GitHub Script

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Find Exisitng Comment
        uses: actions/github-script@v5
        id: find-comment
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
             const prComments = await github.rest.issues.listComments({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo
             })

             let existingComment = prComments.data.find((comment) => { 
              return comment.body.includes("Your Terraform Plan")
             })

             //use id to update commnet, else create...
             if(existingComment) {
               console.log("Should Update")
               github.rest.issues.updateComment({
                 comment_id: existingComment.id,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 body: existingComment.body + '  I updated this comment at ' + Date.now()
               })
             }
             else {
               console.log("Should Add New")
               github.rest.issues.createComment({
                 issue_number: context.issue.number,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 body: 'Your Terraform Plan.'
               })
             }


             
           
